In [1]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt
import copy 
#PUNTO A
def columnas (A,n):
    vector=np.array([])
    if n<=np.shape(A)[1]:
        for i in range(0,np.shape(A)[0]):
            vector=np.append(vector,A[i][n])
    else:
        "La columna indicada sobrepasa el índice de columnas de la matriz"
    return vector


                   
def multiplicador_matrices (A,B):
    dim_A=np.shape(A)
    dim_B=np.shape(B)
    matriz_multi=np.zeros(shape= (dim_A[0],dim_B[1]))
    if dim_A[1]==dim_B[0]:
        for i in range(0,np.shape(A)[0]) :
            for j in range(0,np.shape(B)[1]):
                matriz_multi[i][j]=np.dot(A[i],columnas(B,j))
    else:
        return ("Las matrices no se pueden multiplicar, maestro")

    return matriz_multi
Matriz_a=np.array([[5,-4,-2],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])
Vector_a=np.array([[5],[-2],[-3]])
Matriz_b1=np.array([[0,-1,-1,3],[5,-5,-2,2],[1,0,4,5]])
Matriz_b2=np.array([[0,-3],[-2,-1],[3,-3]])
Matriz_c1=np.array([[2,-5,5,1],[5,2,-7,-6],[6,1,7,4],[5,4,1,-5]])
Matriz_c2=np.array([[0,4,-7,1,-6],[-1,-6,-5,1,1],[2,1,6,5,5],[-3,-6,6,3,5]])
Op_a=multiplicador_matrices(Matriz_a,Vector_a)
Op_b=multiplicador_matrices(Matriz_b1,Matriz_b2)
Op_c=multiplicador_matrices(Matriz_c1,Matriz_c2)
print("Note que en el caso de la operación de matrices c se tiene que M1 por M2 es: ", Op_c, " pero M2 por M1 no se puede realizar" \
".Por lo tanto, la multiplicación de matrices no es conmutativa en general.")

#PUNTO B
#Primero vamos a crear una función que cree una matriz triangular
def reduccion_gauss(A):
    n_filas, n_columnas = np.shape(A)

    for i in range(n_filas):
        if A[i][i] == 0:
            
            return "La matriz no se puede triangularizar debido a un elemento diagonal igual a cero."

        for j in range(i + 1, n_filas):
            factor = A[j][i] / A[i][i]
            for k in range(n_columnas):
                A[j][k] -= factor * A[i][k]

    return A
#Ahora creamos una función que separa los coeficientes del sistema del vector de constantes
def coeficientes_vector(A):
    vector_constantes = A[:, -1]
    A = A[:, :-1]

    return A, vector_constantes
#Usamos el código de la clase para hallar el vector solución
def back_substitution(A, b): 
    n = np.shape(A)[0]

    x = np.zeros(n)

    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(n-1,i,-1):
            sum -= A[i,j]*x[j]
        x[i] = sum/A[i,i]

    return x
A=np.array([[3,1,-1,2],[1,-2,1,0],[4,-1,1,3]])
B=np.array([[1,1,1,0],[-8,0,10,0],[-8,4,0,6]])
Reducida_A=reduccion_gauss(A)
Reducida_B=reduccion_gauss(B)
Sol_A=back_substitution(coeficientes_vector(A)[0],coeficientes_vector(A)[1])
Sol_B=back_substitution(coeficientes_vector(B)[0],coeficientes_vector(B)[1])
Sol_B



Note que en el caso de la operación de matrices c se tiene que M1 por M2 es:  [[  12.   37.   47.   25.   13.]
 [   2.   37. -123.  -46.  -93.]
 [   1.    1.   19.   54.   20.]
 [  13.   27.  -79.   -1.  -46.]]  pero M2 por M1 no se puede realizar.Por lo tanto, la multiplicación de matrices no es conmutativa en general.


array([-0.39473684,  0.71052632, -0.31578947])

In [5]:
Reducida_A

array([[ 3,  1, -1,  2],
       [ 0, -2,  1,  0],
       [ 0,  0,  1,  0]])

In [2]:
Sol_A

array([ 0.66666667, -0.        ,  0.        ])