In [28]:
#Ejercicio 5-Raices polinomios
import numpy as np
import sympy as sym
x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)

def GetLaguerre(n, x):
    if n == 0:
        return sym.Pow(1, 1)
    elif n == 1:
        return 1 - x
    else:
        laguerre_n_minus_1 = GetLaguerre(n - 1, x)
        laguerre_n_minus_2 = GetLaguerre(n - 2, x)
        return ((2 * n - 1 - x) * laguerre_n_minus_1 - (n - 1) * laguerre_n_minus_2) / n


def GetDLaguerre(n,x):
    Pn = GetLaguerre(n,x)
    return sym.diff(Pn,x,1)

def GetNewton(f,df,xn,itmax=500,precision=1e-10):
    
    error = 1.
    it = 0
    
    while error >= precision and it < itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(xn)
            
            error = np.abs(f(xn)/df(xn))
            
        except ZeroDivisionError:
            print('Zero Division')
            
        xn = xn1
        it += 1
        
    if it == itmax:
        return False
    else:
        return xn
    
def GetRootsGLag(f,df,x,tolerancia = 14):
    
    Roots = np.array([])
    
    for i in x:
        
        root = GetNewton(f,df,i)
    
        croot = np.round( root, tolerancia )
        
        if croot not in Roots:
            Roots = np.append(Roots, croot)
                
    Roots.sort()
    
    return Roots

def GetAllRootsGLag(n):

    xn = np.linspace(0,n+((n+1)*np.sqrt(n)),100)
    
    Laguerre = []
    DLaguerre = []
    
    for i in range(n+1):
        Laguerre.append(GetLaguerre(i,x))
        DLaguerre.append(GetDLaguerre(i,x))
    
    poly = sym.lambdify([x],Laguerre[n],'numpy')
    Dpoly = sym.lambdify([x],DLaguerre[n],'numpy')
    Roots = GetRootsGLag(poly,Dpoly,xn)
    
    return Roots

def GetRootsAllPoly (n):
  
    Roots=[]
    for i in range(1,n+1):
        Roots_n=GetAllRootsGLag(i)
        Roots.append(Roots_n)
        
    return Roots
raices_20_polinomios=GetRootsAllPoly(20)
raices_20_polinomios

[array([1.]),
 array([0.58578644, 3.41421356]),
 array([0.41577456, 2.29428036, 6.28994508]),
 array([0.32254769, 1.7457611 , 4.5366203 , 9.39507091, 9.39507091]),
 array([ 0.26356032,  1.41340306,  3.59642577,  7.08581001, 12.64080084]),
 array([ 0.2228466 ,  1.1889321 ,  2.99273633,  5.77514357,  9.83746742,
        15.98287398]),
 array([ 0.19304368,  1.0266649 ,  2.56787674,  4.90035308,  8.18215344,
        12.73418029, 12.73418029, 19.39572786]),
 array([ 0.17027963,  0.90370178,  2.25108663,  4.26670017,  7.0459054 ,
        10.75851601, 15.74067864, 22.86313174]),
 array([ 0.15232223,  0.80722002,  2.00513516,  3.78347397,  6.20495678,
         9.37298525, 13.46623691, 13.46623691, 18.83359779, 26.37407189]),
 array([ 0.13779347,  0.72945455,  1.8083429 ,  3.4014337 ,  5.55249614,
         8.33015275, 11.84378584, 16.27925783, 21.99658581, 29.92069701,
        29.92069701]),
 array([ 0.12579644,  0.66541826,  1.64715055,  3.09113814,  5.0292844 ,
         7.50988786, 10.605951 